### ISSUE TITLE
Selenium server/jar needed?

### ISSUE THREAD

**Issue by simiroll** [simonradier/node-red-contrib-simple-webdriver#10]
Hi I installed the following:
- npm install -g chromedriver
- npm install -g --unsafe-perm node-red
- npm install node-red-contrib-simple-webdriver (install as separate project testing only)

Started the node-red and added an open browser flow but it shows:
Error: connect ECONNREFUSED 127.0.0.1:9515
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

Also the open browser flow ask for "Server", so do I have to start a selenium server first?
How should it be installed and started?

**Comment by simonradier** [comment]
Hi @simiroll

I think you forget to launch the `chromedriver`.
You must launch it to allow the automation of chrome action.

Tell me if it works.

Best regards,

**Comment by simiroll** [comment]
Found out I need to use `apk add chromium-chromedriver` for docker

https://stackoverflow.com/questions/55111180/selenium-python-no-such-file-or-directory-usr-local-bin-chromedriver-but-it

**Comment by simonradier** [comment]
Ok, so I guess it's working?

**Comment by simiroll** [comment]
> Ok, so I guess it's working?
Yes thank you
