### ISSUE TITLE
Typos, bugs and enhancement request

### ISSUE THREAD

**Issue by leopoldoferreira** [simonradier/node-red-contrib-simple-webdriver#11]
Hey Critik! How are u doing? There are minor problems that I keep stumbling upon, If its ok with you Ill keep reporting then once I dont have the proficiency on js/ts (yet) to correct than and pull.

The "Clear the element value before sending the keys." from Send Keys isnt working, It doesnt even ask to deploy, keep unchecked =/
On the references, there are some links that point to node-red-contrib-selenium-wd2, other that is missing a dash ".../node-red-contrib-simplewebdriver" and maybe others
Clik On - inside the properties of click on

Its there a way to send special keys to the browser without passing a By? Just sent a F1 or a Tab to the browser without having to pass a selector.
Like this press key
![image](https://user-images.githubusercontent.com/21108134/196508062-af8c88ac-8b1d-4ec1-b7f3-933e83b5f625.png)

I would be very glad if on Click On, one could right click with a set time between each click
![image](https://user-images.githubusercontent.com/21108134/196507900-8d8c3747-0c75-4b59-af04-d8c77f3d0b06.png)

Screenshot from [node-red-contrib-puppeteer-new](https://github.com/d0uub/node-red-contrib-puppeteer-new)

**Comment by leopoldoferreira** [comment]
![image](https://user-images.githubusercontent.com/21108134/196519829-727e767a-3ba2-494f-8567-37a4822ab059.png)
The Wait For from Run Script is with the same behavior as Send Keys clear element.

**Comment by simonradier** [comment]
Hello @leopoldoferreira,

I updated the package to alpha11 to correct the two following issues : 
* clearVal does not work (there was a typo inside the node properties)
* some links still point to wd2 package

For the sendkeys, it is required to push it to an element (cf. [sendkeys webdriver spec](https://www.w3.org/TR/webdriver2/#element-send-keys). You may simulate this behavior by setting a `By : tagName` and a `Target : body`, but I'm not found of making this "silently".

To push special keys, you can use the following [codes](https://www.w3.org/TR/webdriver2/#keyboard-actions) like `\uE003`.

For the `click-on`, could you create another issue please? I would like to split bug and feature request.

Best regards,
