### ISSUE TITLE
Change session(cookie) not working

### ISSUE THREAD

**Issue by simiroll** [simonradier/node-red-contrib-simple-webdriver#12]
Hi tried using the change cookie flow to update the session(e.g. PHPSESSID, JSESSIONID, etc), neither providing a cookie json object nor fill in the flow doesn't work. Added a refresh page flow after it didn't work as well.

While changing those values in chrome application tab works.

**Comment by simonradier** [comment]
Hi @simiroll,

Could you give me an example workflow?

**Comment by simonradier** [comment]
Closed : No reply from requester.
