### ISSUE TITLE
Click On Feature Request

### ISSUE THREAD

**Issue by leopoldoferreira** [simonradier/node-red-contrib-simple-webdriver#15]
@simonradier could you please add a feature to the Click On node?

I would be very glad if on Click On, one could choose between left,right or middle click, multiple times, with a set delay between, just like this one from [node-red-contrib-puppeteer-new](https://github.com/d0uub/node-red-contrib-puppeteer-new)
![image](https://user-images.githubusercontent.com/21108134/196507900-8d8c3747-0c75-4b59-af04-d8c77f3d0b06.png)

On a side note, could you hit me up at leopoldoferreira@live.com with an email of yours? I would love to ask some stuff to you
Thanks in advance!

**Comment by simonradier** [comment]
Hi @leopoldoferreira,

For the "Left, Right & Middle Click", I'll try to add it, but it is more complicated than it looks. The webdriver standard has the [`element.click`](https://www.w3.org/TR/webdriver2/#element-click) which is only left click. Other type of click relies on "[Action](https://www.w3.org/TR/webdriver2/#actions)" API which is more complicated to use. It requires to detect the retreive the position of the element, scroll to it and then move a "cursor object" to it. My ETA is at least few weeks.

For the loop part, I'm still thinking if it should be embedded in the click node. It creates few questions which must be addressed. I may implement this part but later and it could be addressed with a function node.

Best regards,

**Comment by leopoldoferreira** [comment]
@simonradier , as of right now I don't need anymore, since you made the script node, yesterday I did a work around and did what I needed.
Thank you very much for this palette. I'm a fan of your work!
Since you said its not easy and I dont need, you can close this because I'm good already 👍
