### ISSUE TITLE
Switch Frame node

### ISSUE THREAD

**Issue by iproud** [simonradier/node-red-contrib-simple-webdriver#23]
Is it possible to build a switch frame node?

**Comment by simonradier** [comment]
Hi,

Sorry for the late reply. I'll try to push an update this week to support this feature.

Best regards,

**Comment by simonradier** [comment]
Hello @iproud,

Check out the 2.1.0 version and tell me if it works as expected.

Best regards,

**Comment by iproud** [comment]
Hi @simonradier,

Works perfectly as expected. Thank you so much!

**Comment by simonradier** [comment]
Your welcome.
