### ISSUE TITLE
could you please make the "Find Elements" avaliable?

### ISSUE THREAD

**Issue by rexchoi1983** [simonradier/node-red-contrib-simple-webdriver#29]
hi simon,

thanks to your contrib!
but in my case, i have to get elements in a website. i see the argument names multiple in function "findElement" in webdriver.js.
i try to clone your repository, and add node "find elements" by modifing the copy of find-element.html and find-element.ts.
but i don't know how to compile dist. i am so sorry i am not familiar with create node for node-red.
my temporary way is modifing the npm module that change "multiple" default value from false to true.
but that is not a good way...
so could u help me out, or publish a new version for that issue?
thank u for all.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/40167113/210399195-dd6d0b9e-d78f-4c1c-a369-c73b0a469e8e.png">

**Comment by simonradier** [comment]
Hi @rexchoi1983,

Could you detail a little bit more what you need. I'm not sure you'll need to rebuild my package.

Best regards,

**Comment by rexchoi1983** [comment]
hi simon，

thanks for replying me.
for example, while i search something in google, it will return multiple records.
just like while i use xpath like "//div[@classs='yuRUbf']", i should get an array. 
but the "find element" mode just return first element which xpath found, i need that array.
now it works by changing parameter of "multiple" from false to true.


and i have another advice. while i use chinese character in xpath, webdriver-manager will return a bad request(400) error.
for example "//a[@placeholder='请输入密码']", i will get that error.
because while http request send it with utf-8 encoding, this chinese character encode to 3 bytes for on character.
so i modified call function in http-client.js, encodes json string into unicode string.

thanku simon!

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/40167113/210468212-91b79db3-f698-4e6d-9d46-19b782fe1988.png">

**Comment by simonradier** [comment]
Hi @rexchoi1983,

For the first requirement which is the ability to use "findElements" there is a small cheat which allow you to use it without the need to rebuild the packages.

Here an nodered flow exemple (to import) : 
```
[{"id":"2bc0c83e28a6bbee","type":"debug","z":"2137b1ab4093545e","name":"List of elements","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"elements","targetType":"msg","statusVal":"","statusType":"auto","x":820,"y":60,"wires":[]}]
```
It uses a function node to use the `browser` member of msg (which is required by the node to work).

I'll update the node to allow the use of findElements API in a more "standard way"

For the chinese characters, could you give me a nodered flow example which generate the error?

Best regards,

**Comment by rexchoi1983** [comment]
hi simon,

thanks for your advice, that's very helpful!

i upload a sample flow, please try it.
you could see error message in console of nodered.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/40167113/210580165-89ebb318-83ba-4a31-9d4e-87434038efb5.png">

i use wireshark to capture package,  problem is here:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/40167113/210580633-bc98ba4b-cfe0-400f-801d-68e75c1f529f.png">

if i encode character into unicode string, it will work fine:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/40167113/210581221-cbb13bbd-e641-4662-9432-761f49d414be.png">

i am not very good at nodejs, maybe that is not a good way to fixit. it's just my little suggestion.  i wish it can be helpful.

thanks again!!

[sample_flow.json.txt](https://github.com/simonradier/node-red-contrib-simple-webdriver/files/10344999/sample_flow.json.txt)

**Comment by simonradier** [comment]
Thanks! I'll try to correct this next week.

**Comment by rexchoi1983** [comment]
thank u simon! looking forward to the next version!

**Comment by simonradier** [comment]
@rexchoi1983 : the new 0.2.2 version has corrected the chinese character error.
It was quite simple, the following code was not correct : `httpOptions.headers['Content-Length'] = sBody.length`, it was counting the number of characters, not the number of bytes.
The update `httpOptions.headers['Content-Length'] = new Blob([sBody]).size` corrected this.

Could you try and tell me if it is ok on your side?

Ps : Still working on an update to expose findElements.

**Comment by rexchoi1983** [comment]
hi, simon:

the new version fixes chinese character well. that's great!
it indeed a very simple way to fix, so cool!!
and i also expect the  new version for updating feature of "find elements" .
thanks again, simon!

**Comment by simonradier** [comment]
Hi,

I made a new 0.3.0 version. I'll let you do some test.
* Find Element node allow to retreive multiple element
* All node with are based on Element input can now use multiple elements. A mode field allow to defined the expected behavior (check the doc and the example flow n°4).

Tell me if it works as expected.

Best regards,
