### ISSUE TITLE
Since 0.2.2 Release, "Can't open an instance of chrome"

### ISSUE THREAD

**Issue by iproud** [simonradier/node-red-contrib-simple-webdriver#30]
Since the 0.2.2 Release the Open Browser Node fails with following error:
{"message":"ReferenceError: Blob is not defined","source":{"id":"c50c7b6367693c29","type":"open browser","count":1},"stack":"ReferenceError: Blob is not defined\n    at /data/node_modules/@critik/simple-webdriver/dist/utils/http-client.js:38:57\n    at new Promise (<anonymous>)\n    at Object.call (/data/node_modules/@critik/simple-webdriver/dist/utils/http-client.js:33:12)\n    at Object.call (/data/node_modules/@critik/simple-webdriver/dist/api.js:36:39)\n    at WebDriver.start (/data/node_modules/@critik/simple-webdriver/dist/webdriver.js:383:34)\n    at NodeOpenBrowserConstructor._inputCallback (/data/node_modules/node-red-contrib-simple-webdriver/dist/nodes/open-browser.js:47:40)\n    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26\n    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)\n    at NodeOpenBrowserConstructor.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)\n    at NodeOpenBrowserConstructor.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)"}

**Comment by iproud** [comment]
Node-Red verson 3.0.2
node-red-contrib-simple-webdriver 0.2.2

**Comment by simonradier** [comment]
It was a bug on a dependencies. Could you try to do a clean install again. It should work now.

**Comment by iproud** [comment]
Spot on! That fixed it!

**Comment by iproud** [comment]
Perfect! Always happy to help out with any testing. Happy to close this now
