### ISSUE TITLE
Screenshot of class/id

### ISSUE THREAD

**Issue by bakman2** [simonradier/node-red-contrib-simple-webdriver#41]
Currently it appears that only a screenshot of the whole page can be made. 
Would be nice to make it possible to screenshot a of specific element.

**Comment by simonradier** [comment]
Hi @bakman2 ,

Sorry, I had to pause a bit the project. I'll check if it can be done in an incoming release.

Best regards,

**Comment by simonradier** [comment]
Done in version 0.4.1.

Best regards,
