### ISSUE TITLE
Screenshot and notify?

### ISSUE THREAD

**Issue by FabioEight** [simonradier/node-red-contrib-simple-webdriver#44]
Hello, thanks for your work on this!

I was wondering if there is a tested way to retrieve a webpage screenshot and then use it via notify service of Home Assistant.
Basically, the target is to get a screenshot of a webpage via notification.

Thank you!

**Comment by simonradier** [comment]
Hi @FabioEight,

Thanks for your feedback.
I don't know the capability of Home Assistant. If there is an API to push an image to Home Assistant you could us it to push the image you have generated. I'm not sure I can help you on this. 
At least it is possible to generate an image from a webpage and push it to an API with a protocol supported by Node-red.
For the compatibility with Home Assistant, you'll have to dig on Google API capabilities.

Sorry!

**Comment by simonradier** [comment]
You have the image in base64 in the msg.payload after the screenshot node.

Does it answer your request?
