### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by franco-101** [simonradier/node-red-contrib-simple-webdriver#45]
Hello,

First off awesome application / palette, if you send me a link I’ll buy you a coffee.

I am trying to inject something into the local storage, some user session data, so that the site auto logins. 

Example 

driver.executeScript(function () {
    localStorage.setItem("Id", '{\"_expired\":0,\"_value\":\"133\"}');
})

Would the run script node work?

Would you have any ideas how to go about this?

Thanks

**Comment by simonradier** [comment]
Hi @franco-101 ,

Thanks!

Sorry for the late reply. It should work as it is executed in the context of the web page.
Were you able to figure out your issue?

Best regards,

**Comment by franco-101** [comment]
@simonradier 
Everything is working thanks!
