### ISSUE TITLE
Click on browser alert (ok / cancel) 

### ISSUE THREAD

**Issue by similonpascal** [simonradier/node-red-contrib-simple-webdriver#58]
Hi 
There is a possibility to click on an alert browser with one node ?
I think ther is no node "driver" to manage some functionalities like click on alert window

For example : 
```
//Click the link to activate the alert
await driver.findElement(By.linkText('See an example alert')).click();

// Wait for the alert to be displayed
await driver.wait(until.alertIsPresent());

// Store the alert in a variable
let alert = await driver.switchTo().alert();

//Store the alert text in a variable
let alertText = await alert.getText();

//Press the OK button
await alert.accept();

// Note: To use await, the above code should be inside an async function
  
```

Some interactions with alert, but also other options directly with the driver ?
https://www.selenium.dev/documentation/webdriver/interactions/alerts/

**Comment by simonradier** [comment]
Hi @similonpascal,

Sorry for the late reply, you have a msg.driver component which is accessible directy. I updated  the package to 0.4.3 and simple-webdriver to 0.3.0. You can access a msg.driver object which exposes an alert member with the following methods :
* accept
* dismiss
* getText
* sendText(text: string).

Please let me know if it answers your issue.

Best regards,

**Comment by similonpascal** [comment]
Hi Simon,

We've updated the package as you mention.

Sorry for my late answer, we just try, but i don't think that we do correct.

We use from a function node  : 
- msg.driver.alert.accept()  (drive seems to not exist)
- msg.driver.alert().accept() (msg.driver is not a function)
- msg.browser.alert().accept() ; (not a function)
- msg.browser.alert.accept ; (alert not exist)

This doesn't work for us, can you help me to say what i miss ?
