### ISSUE TITLE
Error - Incorrect HTTP header

### ISSUE THREAD

**Issue by leopoldoferreira** [simonradier/node-red-contrib-simple-webdriver#7]
I install my webdriver based on node-red-contrib-selenium-webdriver, which works ok but stop my nodered when I try to use set value based on selectors: TypeError: By[node.selector] is not a function

I uninstall him and install simple-webdriver, but, I cant connect on the server...
Given the command: `webdriver-manager start --status` the result is:
webdriver-manager: using global installed version 12.1.8
[10:46:24] I/start - java -Dwebdriver.gecko.driver=C:\Users\lfpaula\AppData\Roaming\npm\node_modules\webdriver-manager\selenium\geckodriver-v0.31.0.exe -Dwebdriver.chrome.driver=C:\Users\lfpaula\AppData\Roaming\npm\node_modules\webdriver-manager\selenium\chromedriver_106.0.5249.61.exe -jar C:\Users\lfpaula\AppData\Roaming\npm\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar -port 4444
[10:46:24] I/start - seleniumProcess.pid: 17916
10:46:24.944 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
10:46:25.005 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2022-10-07 10:46:25.043:INFO::main: Logging initialized @258ms to org.seleniumhq.jetty9.util.log.StdErrLog
10:46:25.268 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
10:46:25.402 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444

I tried https://localhost:4444,  https://localhost:4444/wd/hub, which both are reacheable by Node-red, but:

7 Oct 10:44:08 - [info] [open browser:4bc499f681acd9e5] http://localhost:4444 is reacheable by Node-red
[TRACE][2022-10-07T13:44:11.574Z][Object.call|C:\Users\lfpaula\.node-red\node_modules\@critik\simple-webdriver\dist\api.js:30] Calling : POST http://localhost:4444/session
7 Oct 10:44:11 - [error] [open browser:4bc499f681acd9e5] Can't open an instance of chrome
7 Oct 10:44:11 - [error] [open browser:4bc499f681acd9e5] Error: HTTPError : Incorrect HTTP header 'content-type', expected 'application/json'

About a flow example, its only the open browser changing the port, everything else on default.

Is there a way to change the type?
Should I use other webdriver or a different version of chromedrive that works?

**Comment by simonradier** [comment]
Hello,

Thanks for your message. The error is caused by webdriver-manager which is "old" (no update in 1 year) and rely on selenium `3.141.59` which is [an very outdated version](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.141.59).
I advise you to switch to a `chromedriver` npm package which should work.

Tell me if it works.

Best regards,

**Comment by leopoldoferreira** [comment]
Working flawlessly, thank you very much for the quick response.
