### ISSUE TITLE
Navigate To: URL is mandatory

### ISSUE THREAD

**Issue by Sungray** [simonradier/node-red-contrib-simple-webdriver#8]
![image](https://user-images.githubusercontent.com/3531871/194701701-afdb8ec2-488f-4908-8df9-bc94c77d0350.png)

URL shouldn't be mandatory as it can be set through msg.url. That, or the URL parameter in the node should be overwritten by the msg.url, not the other way around.

**Comment by simonradier** [comment]
Thanks @Sungray for pointing out this issue. It has been corrected in alpha9-1.

Best regardsn
